--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authors (
    id bigint NOT NULL,
    biography character varying(3000),
    birth_date date,
    created_at timestamp(6) without time zone,
    death_date date,
    first_name character varying(255) NOT NULL,
    image_url character varying(255),
    last_name character varying(255),
    updated_at timestamp(6) without time zone,
    website character varying(255),
    nationality character varying(255),
    pen_name character varying(255),
    photo_url character varying(255)
);


--
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_authors (
    book_id bigint NOT NULL,
    author_id bigint NOT NULL
);


--
-- Name: book_characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_characters (
    id bigint NOT NULL,
    character_name character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(3000),
    favorite boolean,
    notes character varying(3000),
    role character varying(255),
    book_id bigint NOT NULL
);


--
-- Name: book_characters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_characters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_characters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_genres (
    book_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


--
-- Name: book_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_locations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(3000),
    favorite boolean,
    location_name character varying(255),
    location_type character varying(255),
    notes character varying(3000),
    book_id bigint NOT NULL
);


--
-- Name: book_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_timeline_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_timeline_events (
    id bigint NOT NULL,
    chapter_name character varying(255),
    created_at timestamp(6) without time zone,
    event_description character varying(5000),
    event_order integer,
    event_title character varying(255),
    notes character varying(3000),
    page_number integer,
    spoiler_warning boolean,
    book_id bigint NOT NULL
);


--
-- Name: book_timeline_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_timeline_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_timeline_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    book_format character varying(255),
    cover_image_url character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(5000),
    isbn character varying(255),
    page_count integer,
    publication_date date,
    publisher character varying(255),
    reading_status character varying(255),
    series_name character varying(255),
    series_number double precision,
    subtitle character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    author_id bigint,
    library_id bigint,
    average_rating double precision,
    date_added date,
    dnf boolean,
    favorite boolean,
    isbn10 character varying(255),
    isbn13 character varying(255),
    owned boolean,
    published_date date,
    user_rating double precision,
    wishlist boolean,
    audiobook_length_seconds integer,
    current_status character varying(255),
    language character varying(255),
    personal_notes character varying(5000),
    primary_format character varying(255),
    catalog_provider character varying(255),
    catalog_provider_id character varying(255),
    edition_format character varying(255),
    narrator character varying(255),
    CONSTRAINT books_book_format_check CHECK (((book_format)::text = ANY ((ARRAY['PHYSICAL'::character varying, 'EBOOK'::character varying, 'AUDIOBOOK'::character varying])::text[]))),
    CONSTRAINT books_current_status_check CHECK (((current_status)::text = ANY ((ARRAY['TBR'::character varying, 'CURRENTLY_READING'::character varying, 'COMPLETED'::character varying, 'DNF'::character varying, 'PAUSED'::character varying])::text[]))),
    CONSTRAINT books_primary_format_check CHECK (((primary_format)::text = ANY ((ARRAY['PHYSICAL_BOOK'::character varying, 'E_BOOK'::character varying, 'AUDIO_BOOK'::character varying])::text[]))),
    CONSTRAINT books_reading_status_check CHECK (((reading_status)::text = ANY ((ARRAY['TBR'::character varying, 'CURRENTLY_READING'::character varying, 'COMPLETED'::character varying, 'DNF'::character varying, 'PAUSED'::character varying])::text[])))
);


--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.genres (
    id bigint NOT NULL,
    description character varying(1000),
    name character varying(255) NOT NULL
);


--
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journal_entries (
    id bigint NOT NULL,
    chapter_name character varying(255),
    content character varying(10000),
    created_at timestamp(6) without time zone,
    mood character varying(255),
    page_number integer,
    spoiler_warning boolean,
    title character varying(255),
    reading_experience_id bigint NOT NULL,
    favorite boolean
);


--
-- Name: journal_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: libraries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.libraries (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    name character varying(255) NOT NULL,
    selected_theme character varying(255),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: libraries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.libraries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libraries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: music_associations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.music_associations (
    id bigint NOT NULL,
    artist character varying(255),
    association_description character varying(2000),
    association_type character varying(255),
    created_at timestamp(6) without time zone,
    embed_url character varying(255),
    external_url character varying(255),
    music_type character varying(255),
    notes character varying(3000),
    platform character varying(255),
    playlist_name character varying(255),
    title character varying(255),
    book_id bigint,
    reading_experience_id bigint,
    CONSTRAINT music_associations_association_type_check CHECK (((association_type)::text = ANY ((ARRAY['WHOLE_BOOK'::character varying, 'SERIES'::character varying, 'READING_EXPERIENCE'::character varying, 'CHAPTER'::character varying, 'SCENE'::character varying, 'CHARACTER'::character varying, 'RELATIONSHIP'::character varying, 'MOOD'::character varying, 'TROPE'::character varying, 'READING_MEMORY'::character varying, 'GENERAL_VIBE'::character varying])::text[]))),
    CONSTRAINT music_associations_music_type_check CHECK (((music_type)::text = ANY ((ARRAY['SONG'::character varying, 'PLAYLIST'::character varying, 'ALBUM'::character varying, 'ARTIST'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT music_associations_platform_check CHECK (((platform)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'APPLE_MUSIC'::character varying, 'YOUTUBE'::character varying, 'YOUTUBE_MUSIC'::character varying, 'SOUNDCLOUD'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: music_associations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.music_associations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.music_associations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quotes (
    id bigint NOT NULL,
    chapter_name character varying(255),
    character_name character varying(255),
    created_at timestamp(6) without time zone,
    favorite boolean,
    notes character varying(1000),
    page_number integer,
    quote_text character varying(5000) NOT NULL,
    book_id bigint NOT NULL
);


--
-- Name: quotes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reading_experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_experiences (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    current_experience boolean,
    current_listening_seconds integer,
    current_page integer,
    dnf_reason character varying(2000),
    experience_number integer,
    experience_type character varying(255),
    finish_date date,
    format character varying(255),
    listening_speed double precision,
    percent_complete double precision,
    rating double precision,
    review_text character varying(5000),
    start_date date,
    status character varying(255),
    total_listening_seconds integer,
    total_pages integer,
    updated_at timestamp(6) without time zone,
    book_id bigint NOT NULL,
    current_excitement_rating character varying(255),
    current_rating character varying(255),
    emotional_devastation_rating character varying(255),
    excitement_rating character varying(255),
    excitement_while_reading character varying(255),
    final_rating character varying(255),
    horror_rating character varying(255),
    initial_rating character varying(255),
    label character varying(255),
    predicted_rating character varying(255),
    reread_rating character varying(255),
    romance_importance character varying(255),
    romance_notes character varying(5000),
    romance_presence character varying(255),
    romance_rating character varying(255),
    spice_rating character varying(255),
    prompt_responses_json text,
    CONSTRAINT reading_experiences_experience_type_check CHECK (((experience_type)::text = ANY ((ARRAY['FIRST_READ'::character varying, 'REREAD'::character varying, 'FIRST_LISTEN'::character varying, 'RELISTEN'::character varying, 'DNF_ATTEMPT'::character varying, 'PARTIAL_READ'::character varying])::text[]))),
    CONSTRAINT reading_experiences_format_check CHECK (((format)::text = ANY ((ARRAY['PHYSICAL_BOOK'::character varying, 'E_BOOK'::character varying, 'AUDIO_BOOK'::character varying])::text[]))),
    CONSTRAINT reading_experiences_status_check CHECK (((status)::text = ANY ((ARRAY['TBR'::character varying, 'CURRENTLY_READING'::character varying, 'COMPLETED'::character varying, 'DNF'::character varying, 'PAUSED'::character varying])::text[])))
);


--
-- Name: reading_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reading_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reading_experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reading_goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_goals (
    id bigint NOT NULL,
    completed boolean,
    created_at timestamp(6) without time zone,
    current_value integer,
    end_date date,
    goal_name character varying(255),
    goal_type character varying(255),
    start_date date,
    target_value integer,
    user_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: reading_goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reading_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reading_goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    display_name character varying(255),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- Name: book_authors book_authors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT book_authors_pkey PRIMARY KEY (book_id, author_id);


--
-- Name: book_characters book_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_characters
    ADD CONSTRAINT book_characters_pkey PRIMARY KEY (id);


--
-- Name: book_genres book_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_genres
    ADD CONSTRAINT book_genres_pkey PRIMARY KEY (book_id, genre_id);


--
-- Name: book_locations book_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_locations
    ADD CONSTRAINT book_locations_pkey PRIMARY KEY (id);


--
-- Name: book_timeline_events book_timeline_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_timeline_events
    ADD CONSTRAINT book_timeline_events_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- Name: journal_entries journal_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entries
    ADD CONSTRAINT journal_entries_pkey PRIMARY KEY (id);


--
-- Name: libraries libraries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT libraries_pkey PRIMARY KEY (id);


--
-- Name: music_associations music_associations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.music_associations
    ADD CONSTRAINT music_associations_pkey PRIMARY KEY (id);


--
-- Name: quotes quotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT quotes_pkey PRIMARY KEY (id);


--
-- Name: reading_experiences reading_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_experiences
    ADD CONSTRAINT reading_experiences_pkey PRIMARY KEY (id);


--
-- Name: reading_goals reading_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_goals
    ADD CONSTRAINT reading_goals_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: libraries uk9vyhke8v3mhq128kq5oi0vuhc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT uk9vyhke8v3mhq128kq5oi0vuhc UNIQUE (user_id);


--
-- Name: genres ukpe1a9woik1k97l87cieguyhh4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT ukpe1a9woik1k97l87cieguyhh4 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: journal_entries fk1avivcw8ri1dskawtss1dcj30; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_entries
    ADD CONSTRAINT fk1avivcw8ri1dskawtss1dcj30 FOREIGN KEY (reading_experience_id) REFERENCES public.reading_experiences(id);


--
-- Name: book_timeline_events fk5b6k0tl14c9bl0epkav05dc9m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_timeline_events
    ADD CONSTRAINT fk5b6k0tl14c9bl0epkav05dc9m FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_genres fk6ce5ct13whb85xqu83jmceboj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_genres
    ADD CONSTRAINT fk6ce5ct13whb85xqu83jmceboj FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- Name: books fk6gdvp1ko0pawgafhn1hyhsxia; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT fk6gdvp1ko0pawgafhn1hyhsxia FOREIGN KEY (library_id) REFERENCES public.libraries(id);


--
-- Name: reading_goals fk7cujieliuha9vpft4nhc1e4em; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_goals
    ADD CONSTRAINT fk7cujieliuha9vpft4nhc1e4em FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reading_experiences fk89ton9rbqet0m9xnc842a1xsw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_experiences
    ADD CONSTRAINT fk89ton9rbqet0m9xnc842a1xsw FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_authors fkbhqtkv2cndf10uhtknaqbyo0a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT fkbhqtkv2cndf10uhtknaqbyo0a FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: books fkfjixh2vym2cvfj3ufxj91jem7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT fkfjixh2vym2cvfj3ufxj91jem7 FOREIGN KEY (author_id) REFERENCES public.authors(id);


--
-- Name: libraries fkii9s3dpbrehajshdirhol0asr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT fkii9s3dpbrehajshdirhol0asr FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: music_associations fkjcyblo9lo4qts4nv6y1jtjdjs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.music_associations
    ADD CONSTRAINT fkjcyblo9lo4qts4nv6y1jtjdjs FOREIGN KEY (reading_experience_id) REFERENCES public.reading_experiences(id);


--
-- Name: quotes fklus9hhp6i4xchaju7r96r7e2p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT fklus9hhp6i4xchaju7r96r7e2p FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_locations fkm3teoaetiljgs56ivrff9wsf5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_locations
    ADD CONSTRAINT fkm3teoaetiljgs56ivrff9wsf5 FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_authors fko86065vktj3hy1m7syr9cn7va; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT fko86065vktj3hy1m7syr9cn7va FOREIGN KEY (author_id) REFERENCES public.authors(id);


--
-- Name: music_associations fkpc1lla3r8nw1w2qi51dliph4c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.music_associations
    ADD CONSTRAINT fkpc1lla3r8nw1w2qi51dliph4c FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_characters fkth9jatnl99sxp6pku7qw6dc3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_characters
    ADD CONSTRAINT fkth9jatnl99sxp6pku7qw6dc3y FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: book_genres fktqnlma9c5byf3gfqsuu0ebrl5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_genres
    ADD CONSTRAINT fktqnlma9c5byf3gfqsuu0ebrl5 FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- PostgreSQL database dump complete
--
